[template]
src = "backup-objects.conf.tmpl"
dest = "/etc/vertica-backup-objects.conf"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
